January:
  - Category: JSON Schema Sponsorship
    Amount: '250.00'
  - Category: Swag Store
    Amount: '678.26'
  - Category: Bounty Program
    Amount: '1800.00'
  - Category: Community Manager
    Amount: '2000.00'
  - Category: AsyncAPI Conf on Tour 2023
    Amount: '318.98'
February:
  - Category: Bounty Program
    Amount: '400.00'
  - Category: JSON Schema Sponsorship
    Amount: '250.00'
  - Category: Community Manager
    Amount: '2000.00'
  - Category: Swag Store
    Amount: '474.35'
  - Category: AsyncAPI Conf on Tour 2023
    Amount: '675.56'
  - Category: Mentorship Program 2023
    Amount: '4125.00'
March:
  - Category: JSON Schema Sponsorship
    Amount: '250.00'
  - Category: Community Manager
    Amount: '2000.00'
  - Category: Mentorship Program 2023
    Amount: '2475.00'
  - Category: Swag Store
    Amount: '955.03'
  - Category: Bounty Program
    Amount: '200.00'
April:
  - Category: JSON Schema Sponsorship
    Amount: '250.00'
  - Category: Community Manager
    Amount: '2000.00'
  - Category: Mentorship Program 2023
    Amount: '2475.00'
  - Category: Swag Store
    Amount: '607.97'
  - Category: Bounty Program
    Amount: '800.00'
May:
  - Category: JSON Schema Sponsorship
    Amount: '250.00'
  - Category: Community Manager
    Amount: '2000.00'
  - Category: Swag Store
    Amount: '526.51'
  - Category: Bounty Program
    Amount: '800.00'
  - Category: Community Marketing Specialist
    Amount: '1000.00'
June:
  - Category: JSON Schema Sponsorship
    Amount: '250.00'
  - Category: Community Manager
    Amount: '2000.00'
  - Category: Community Marketing Specialist
    Amount: '2000.00'
  - Category: Bounty Program
    Amount: '800.00'
  - Category: Swag Store
    Amount: '526.51'
July:
  - Category: JSON Schema Sponsorship
    Amount: '250.00'
  - Category: Community Manager
    Amount: '2000.00'
  - Category: Bounty Program
    Amount: '1000.00'
  - Category: Swag Store
    Amount: '526.51'
  - Category: Community Marketing Specialist
    Amount: '2000.00'
  - Category: AsyncAPI Conf on Tour 2024
    Amount: '2083.41'
August:
  - Category: JSON Schema Sponsorship
    Amount: '250.00'
  - Category: Community Manager
    Amount: '2000.00'
  - Category: Bounty Program
    Amount: '1800.00'
  - Category: Swag Store
    Amount: '2556.42'
  - Category: Community Marketing Specialist
    Amount: '2000.00'
  - Category: 3rd Party Services
    Amount: '1354.35'
  - Category: AsyncAPI Conf on Tour 2024
    Amount: '1384.70'
September:
  - Category: Bounty Program
    Amount: '3000.00'
  - Category: Swag Store
    Amount: '736.59'
  - Category: Community Manager
    Amount: '2000.00'
  - Category: Community Marketing Specialist
    Amount: '2000.00'
  - Category: JSON Schema Sponsorship
    Amount: '250.00'
  - Category: AsyncAPI Conf on Tour 2024
    Amount: '672.23'
October:
  - Category: Bounty Program
    Amount: '1000.00'
  - Category: Swag Store
    Amount: '882.12'
  - Category: AsyncAPI Conf on Tour 2024
    Amount: '289.78'
  - Category: Community Manager
    Amount: '2000.00'
  - Category: Community Marketing Specialist
    Amount: '2000.00'
  - Category: JSON Schema Sponsorship
    Amount: '250.00'
November:
  - Category: Swag Store
    Amount: '472.36'
  - Category: Community Manager
    Amount: '2000.00'
  - Category: Community Marketing Specialist
    Amount: '2000.00'
  - Category: JSON Schema Sponsorship
    Amount: '250.00'
December:
  - Category: Bounty Program
    Amount: '1400.00'
  - Category: Swag Store
    Amount: '917.99'
  - Category: Community Manager
    Amount: '2000.00'
  - Category: Community Marketing Specialist
    Amount: '2000.00'
  - Category: JSON Schema Sponsorship
    Amount: '250.00'
  - Category: AsyncAPI Conf on Tour 2024
    Amount: '2767.99'
    