- category: "Ambassador Program"
  link: "https://github.com/orgs/asyncapi/discussions/425"
- category: "Google Season of Docs 2023"
  link: "https://github.com/orgs/asyncapi/discussions/961"
- category: "Swag Store"
  link: "https://github.com/orgs/asyncapi/discussions/710"
- category: "Bounty Program"
  link: "https://github.com/orgs/asyncapi/discussions/541"
- category: "3rd Party Services"
  link: "https://github.com/orgs/asyncapi/discussions/295"
- category: "Community Manager"
  link: "https://github.com/orgs/asyncapi/discussions/515"
- category: "AsyncAPI Conf on Tour 2023"
  link: "https://github.com/orgs/asyncapi/discussions/598"
- category: "AsyncAPI Conf on Tour 2024"
  link: "https://github.com/orgs/asyncapi/discussions/1018"
- category: "Mentorship Program 2023"
  link: "https://github.com/orgs/asyncapi/discussions/689"
- category: "JSON Schema Sponsorship"
  link: "https://github.com/orgs/asyncapi/discussions/1017"
- category: "Community Marketing Specialist"
  link: "https://github.com/orgs/asyncapi/discussions/1176"
