name: List of all the tools used in AsyncAPI

on: 
  workflow_dispatch:
  schedule:
  #every day at midnight
  - cron: "15 0 * * 1"

jobs:
  meetings:
      if: github.repository == 'asyncapi/website'
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      name: Regenerate tools.json
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Install dependencies
          run: npm install
        - name: Regenerate
          run: npm run generate:tools
        - name: Create Pull Request with new tools.json version
          uses: peter-evans/create-pull-request@v3
          with:
            token: ${{ secrets.GH_TOKEN }}
            commit-message: 'chore: update tools.json'
            committer: asyncapi-bot <info@asyncapi.io>
            author: asyncapi-bot <info@asyncapi.io>
            title: 'chore: update meetings.json and newsrooom_videos.json'
            branch: update-meetings/${{ github.job }}
        - if: failure() # Only, on failure, send a message on the 94_bot-failing-ci slack channel
          name: Report workflow run status to Slack
          uses: 8398a7/action-slack@v3
          with:
            status: ${{ job.status }}
            fields: repo,action,workflow
            text: 'AsyncAPI Tools workflow failed'
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_FAIL_NOTIFY }}